apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Chart.Name }}-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvtest
  template:
    metadata:
      labels:
        app: pvtest
    spec:
      containers:
        {{- range $i := until 30 }}
        - name: "{{ $.Chart.Name }}-{{ $i }}"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          volumeMounts:
            - name: "{{ $.Chart.Name }}-volume{{ $i }}"
              mountPath: /usr/data
        {{- end }}
      volumes:
        {{- range $i := until 30 }}
        - name: "{{ $.Chart.Name }}-volume{{ $i }}"
          persistentVolumeClaim:
            claimName: "{{ $.Chart.Name }}-pvc{{ $i }}"
        {{- end }}
