apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Chart.Name }}-ns
  labels:
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"