{{- range $i := until 30 }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $.Chart.Name }}-pvc{{ $i }}"
spec:
  storageClassName: {{ $.Values.persistence.storageClassName }}
  accessModes:
    - {{ range $mode := $.Values.persistence.accessModes }}{{ $mode }}{{ end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}

---

{{- end }}