# Default values for pod-and-pv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 50
snapshotCount: 10

namespace: pvtest

image:
  repository: nginx
  tag: latest

persistence:
  storageClassName: lvms-vg1
  accessModes:
    - ReadWriteOnce
  size: 1Gi

